version: '2'

networks:
  app-tier:
    driver: bridge

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    expose:
      - "2181"
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    expose:
      - "9092"
    volumes:
      - 'kafka_data:/bitnami/kafka'
    networks:
      - app-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_INTER_BROKER_USER=interuser
      - KAFKA_INTER_BROKER_PASSWORD=interpassword
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local